import type { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Link from 'src/components/atoms/Link'
import { useEffect, useState } from 'react'
import { useAppDispatch, useAppSelector } from 'src/store'
import { selectCount } from 'src/store/counter'
import { increment, setCounterState } from 'src/store/counter/counterSlice'
import { NextSeo } from 'next-seo'

export const getStaticProps: GetStaticProps = async () => ({
  props: { data: ['Karthick', 'Ragavendran'] }, // will be passed to the page component as props
})

const Home: NextPage = ({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const obj = { title: 'Hello World' }
  const [text, setText] = useState(JSON.stringify(obj))
  const dispatch = useAppDispatch()
  const count = useAppSelector(selectCount)
  useEffect(() => {
    dispatch(setCounterState(data))
  }, [data, dispatch])
  return (
    <div className='container mx-auto space-y-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NextSeo
        title='Next boilerplate.'
        description='A short description goes here which says what goes here.'
      />
      <div>
        {text}
        <div className='flex gap-4 mt-2'>
          {/** @ts-ignore */}
          <button type='button' onClick={() => setText(obj)}>
            Break things
          </button>
        </div>
      </div>
      <div>
        {JSON.stringify(count)}
        <div className='flex gap-4 mt-2'>
          <button
            className='px-2 py-1 border rounded-sm'
            type='button'
            onClick={() => dispatch(setCounterState(8))}
          >
            Reset count
          </button>
          <button
            className='px-2 py-1 border rounded-sm'
            type='button'
            onClick={() => dispatch(increment())}
          >
            Inc{' '}
          </button>
        </div>
      </div>

      <main>
        <Link
          prefetch={false}
          className='hover:underline underline-offset-2'
          href='/sample'
        >
          <a>To sample page &gt; </a>
        </Link>
      </main>

      <footer className='mt-16 text-gray-500'>Next boilerplate</footer>
    </div>
  )
}

export default Home
